config: ./conf/tuning/finetune_joint_tacotron2_hifigan.yaml
print_config: false
log_level: INFO
dry_run: false
iterator_type: sequence
output_dir: exp/22k/tts_finetune_joint_tacotron2_hifigan_raw_char
ngpu: 1
seed: 777
num_workers: 4
num_att_plot: 3
dist_backend: nccl
dist_init_method: env://
dist_world_size: null
dist_rank: null
local_rank: 0
dist_master_addr: null
dist_master_port: null
dist_launcher: null
multiprocessing_distributed: false
unused_parameters: true
sharded_ddp: false
cudnn_enabled: true
cudnn_benchmark: false
cudnn_deterministic: false
collect_stats: false
write_collected_feats: false
max_epoch: 140
patience: null
val_scheduler_criterion:
- valid
- loss
early_stopping_criterion:
- valid
- loss
- min
best_model_criterion:
-   - valid
    - text2mel_loss
    - min
-   - train
    - text2mel_loss
    - min
-   - train
    - total_count
    - max
keep_nbest_models: 5
nbest_averaging_interval: 0
grad_clip: -1
grad_clip_type: 2.0
grad_noise: false
accum_grad: 1
no_forward_run: false
resume: true
train_dtype: float32
use_amp: false
log_interval: 50
use_matplotlib: true
use_tensorboard: true
create_graph_in_tensorboard: false
use_wandb: false
wandb_project: null
wandb_id: null
wandb_entity: null
wandb_name: null
wandb_model_log_interval: -1
detect_anomaly: false
pretrain_path: null
init_param:
- exp/22k/tts_train_tacotron2_raw_char/train.loss.ave_5best.pth:tts:tts.generator.text2mel
- exp/22k/ljspeech_hifigan.v1/generator.pth::tts.generator.vocoder
- exp/22k/ljspeech_hifigan.v1/discriminator.pth::tts.discriminator
ignore_init_mismatch: false
freeze_param: []
num_iters_per_epoch: null
batch_size: 20
valid_batch_size: null
batch_bins: 1600000
valid_batch_bins: null
train_shape_file:
- exp/22k/tts_stats_raw_char/train/text_shape.char
- exp/22k/tts_stats_raw_char/train/speech_shape
valid_shape_file:
- exp/22k/tts_stats_raw_char/valid/text_shape.char
- exp/22k/tts_stats_raw_char/valid/speech_shape
batch_type: numel
valid_batch_type: null
fold_length:
- 150
- 204800
sort_in_batch: descending
sort_batch: descending
multiple_iterator: false
chunk_length: 500
chunk_shift_ratio: 0.5
num_cache_chunks: 1024
train_data_path_and_name_and_type:
-   - dump/22k/raw/tr_no_dev/text
    - text
    - text
-   - dump/22k/raw/tr_no_dev/wav.scp
    - speech
    - sound
-   - dump/22k/xvector/tr_no_dev/xvector.scp
    - spembs
    - kaldi_ark
valid_data_path_and_name_and_type:
-   - dump/22k/raw/dev/text
    - text
    - text
-   - dump/22k/raw/dev/wav.scp
    - speech
    - sound
-   - dump/22k/xvector/dev/xvector.scp
    - spembs
    - kaldi_ark
allow_variable_data_keys: false
max_cache_size: 0.0
max_cache_fd: 32
valid_max_cache_size: null
exclude_weight_decay: false
exclude_weight_decay_conf: {}
optim: adam
optim_conf:
    lr: 1.25e-05
    betas:
    - 0.5
    - 0.9
    weight_decay: 0.0
scheduler: exponentiallr
scheduler_conf:
    gamma: 0.999875
optim2: adam
optim2_conf:
    lr: 1.25e-05
    betas:
    - 0.5
    - 0.9
    weight_decay: 0.0
scheduler2: exponentiallr
scheduler2_conf:
    gamma: 0.999875
generator_first: true
token_list:
- <blank>
- <unk>
- +
- <space>
- о
- а
- и
- н
- в
- е
- т
- і
- с
- р
- д
- л
- у
- к
- м
- п
- я
- з
- ','
- б
- ь
- г
- ч
- й
- ж
- х
- ш
- ю
- ц
- щ
- '?'
- '-'
- ї
- є
- '!'
- ''''
- ф
- .
- '"'
- ґ
- ':'
- /
- „
- <sos/eos>
odim: null
model_conf: {}
use_preprocessor: true
token_type: char
bpemodel: null
non_linguistic_symbols: null
cleaner: null
g2p: g2p_en
feats_extract: fbank
feats_extract_conf:
    n_fft: 1024
    hop_length: 256
    win_length: null
    fs: 22050
    fmin: 80
    fmax: 7600
    n_mels: 80
normalize: global_mvn
normalize_conf:
    stats_file: feats_stats.npz
tts: joint_text2wav
tts_conf:
    text2mel_type: tacotron2
    text2mel_params:
        embed_dim: 512
        elayers: 1
        eunits: 512
        econv_layers: 3
        econv_chans: 512
        econv_filts: 5
        atype: location
        adim: 512
        aconv_chans: 32
        aconv_filts: 15
        cumulate_att_w: true
        dlayers: 2
        dunits: 1024
        prenet_layers: 2
        prenet_units: 256
        postnet_layers: 5
        postnet_chans: 512
        postnet_filts: 5
        output_activation: null
        use_batch_norm: true
        use_concate: true
        use_residual: false
        spk_embed_dim: 192
        spk_embed_integration_type: add
        dropout_rate: 0.5
        zoneout_rate: 0.1
        reduction_factor: 1
        use_masking: true
        bce_pos_weight: 10.0
        use_guided_attn_loss: true
        guided_attn_loss_sigma: 0.4
        guided_attn_loss_lambda: 1.0
        idim: 48
        odim: 80
    vocoder_type: hifigan_generator
    vocoder_params:
        bias: true
        channels: 512
        in_channels: 80
        kernel_size: 7
        nonlinear_activation: LeakyReLU
        nonlinear_activation_params:
            negative_slope: 0.1
        out_channels: 1
        resblock_dilations:
        -   - 1
            - 3
            - 5
        -   - 1
            - 3
            - 5
        -   - 1
            - 3
            - 5
        resblock_kernel_sizes:
        - 3
        - 7
        - 11
        upsample_kernel_sizes:
        - 16
        - 16
        - 4
        - 4
        upsample_scales:
        - 8
        - 8
        - 2
        - 2
        use_additional_convs: true
        use_weight_norm: true
    discriminator_type: hifigan_multi_scale_multi_period_discriminator
    discriminator_params:
        follow_official_norm: true
        period_discriminator_params:
            bias: true
            channels: 32
            downsample_scales:
            - 3
            - 3
            - 3
            - 3
            - 1
            in_channels: 1
            kernel_sizes:
            - 5
            - 3
            max_downsample_channels: 1024
            nonlinear_activation: LeakyReLU
            nonlinear_activation_params:
                negative_slope: 0.1
            out_channels: 1
            use_spectral_norm: false
            use_weight_norm: true
        periods:
        - 2
        - 3
        - 5
        - 7
        - 11
        scale_discriminator_params:
            bias: true
            channels: 128
            downsample_scales:
            - 4
            - 4
            - 4
            - 4
            - 1
            in_channels: 1
            kernel_sizes:
            - 15
            - 41
            - 5
            - 3
            max_downsample_channels: 1024
            max_groups: 16
            nonlinear_activation: LeakyReLU
            nonlinear_activation_params:
                negative_slope: 0.1
            out_channels: 1
        scale_downsample_pooling: AvgPool1d
        scale_downsample_pooling_params:
            kernel_size: 4
            padding: 2
            stride: 2
        scales: 3
    generator_adv_loss_params:
        average_by_discriminators: false
        loss_type: mse
    discriminator_adv_loss_params:
        average_by_discriminators: false
        loss_type: mse
    use_feat_match_loss: true
    feat_match_loss_params:
        average_by_discriminators: false
        average_by_layers: false
        include_final_outputs: true
    use_mel_loss: true
    mel_loss_params:
        fs: 22050
        n_fft: 1024
        hop_length: 256
        win_length: null
        window: hann
        n_mels: 80
        fmin: 0
        fmax: null
        log_base: null
    lambda_text2mel: 1.0
    lambda_adv: 1.0
    lambda_mel: 45.0
    lambda_feat_match: 2.0
    sampling_rate: 22050
    segment_size: 32
    cache_generator_outputs: true
pitch_extract: null
pitch_extract_conf: {}
pitch_normalize: null
pitch_normalize_conf: {}
energy_extract: null
energy_extract_conf: {}
energy_normalize: null
energy_normalize_conf: {}
required:
- output_dir
- token_list
version: '202301'
distributed: false
